package com.iti.ChatCommanServices.model.entity.chat;
// Generated Mar 7, 2019 7:51:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserChat generated by hbm2java
 */
@Entity
@Table(name="user_chat"
        ,catalog="javachatdatabase"
)
public class UserChat  implements java.io.Serializable {


    private Integer chatId;
    private String firstPhoneNumber;
    private String secondPhoneNumber;
    private Set<Chat> chats = new HashSet<Chat>(0);

    public UserChat() {
    }


    public UserChat(String firstPhoneNumber, String secondPhoneNumber) {
        this.firstPhoneNumber = firstPhoneNumber;
        this.secondPhoneNumber = secondPhoneNumber;
    }
    public UserChat(String firstPhoneNumber, String secondPhoneNumber, Set<Chat> chats) {
        this.firstPhoneNumber = firstPhoneNumber;
        this.secondPhoneNumber = secondPhoneNumber;
        this.chats = chats;
    }

    @Id @GeneratedValue(strategy=IDENTITY)


    @Column(name="chat_id", unique=true, nullable=false)
    public Integer getChatId() {
        return this.chatId;
    }

    public void setChatId(Integer chatId) {
        this.chatId = chatId;
    }


    @Column(name="first_phone_number", nullable=false, length=12)
    public String getFirstPhoneNumber() {
        return this.firstPhoneNumber;
    }

    public void setFirstPhoneNumber(String firstPhoneNumber) {
        this.firstPhoneNumber = firstPhoneNumber;
    }


    @Column(name="second_phone_number", nullable=false, length=12)
    public String getSecondPhoneNumber() {
        return this.secondPhoneNumber;
    }

    public void setSecondPhoneNumber(String secondPhoneNumber) {
        this.secondPhoneNumber = secondPhoneNumber;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="userChat")
    public Set<Chat> getChats() {
        return this.chats;
    }

    public void setChats(Set<Chat> chats) {
        this.chats = chats;
    }




}


