package com.iti.ChatCommanServices.model.entity.chat;
// Generated Mar 7, 2019 7:51:46 PM by Hibernate Tools 4.3.1


import com.iti.ChatCommanServices.model.entity.user.User;

import javax.persistence.*;

/**
 * UserGroupChat generated by hbm2java
 */
@Entity
@Table(name="user_group_chat"
    ,catalog="javachatdatabase"
)
public class UserGroupChat  implements java.io.Serializable {


     private UserGroupChatId id;
     private User user;

    public UserGroupChat() {
    }

    public UserGroupChat(UserGroupChatId id, User user) {
       this.id = id;
       this.user = user;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="userGroupchatId", column=@Column(name="user_groupchat_id", nullable=false) ), 
        @AttributeOverride(name="phoneNumber", column=@Column(name="phone_Number", nullable=false, length=20) ) } )
    public UserGroupChatId getId() {
        return this.id;
    }
    
    public void setId(UserGroupChatId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="phone_Number", nullable=false, insertable=false, updatable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


