package com.iti.ChatCommanServices.model.entity.user;
// Generated Mar 7, 2019 7:51:46 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserContactId generated by hbm2java
 */
@Embeddable
public class UserContactId implements java.io.Serializable {


     private String contact;
     private String phoneNumber;

    public UserContactId() {
    }

    public UserContactId(String contact, String phoneNumber) {
       this.contact = contact;
       this.phoneNumber = phoneNumber;
    }
   


    @Column(name="contact", nullable=false, length=20)
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }


    @Column(name="phone_number", nullable=false, length=20)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserContactId) ) return false;
		 UserContactId castOther = ( UserContactId ) other; 
         
		 return ( (this.getContact()==castOther.getContact()) || ( this.getContact()!=null && castOther.getContact()!=null && this.getContact().equals(castOther.getContact()) ) )
 && ( (this.getPhoneNumber()==castOther.getPhoneNumber()) || ( this.getPhoneNumber()!=null && castOther.getPhoneNumber()!=null && this.getPhoneNumber().equals(castOther.getPhoneNumber()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getContact() == null ? 0 : this.getContact().hashCode() );
         result = 37 * result + ( getPhoneNumber() == null ? 0 : this.getPhoneNumber().hashCode() );
         return result;
   }   


}


