package com.iti.ChatCommanServices.model.entity.user;
// Generated Mar 7, 2019 7:51:46 PM by Hibernate Tools 4.3.1


import com.iti.ChatCommanServices.model.entity.chat.UserGroupChat;
import com.iti.ChatCommanServices.model.entity.dto.message.MessageSettings;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
        ,catalog="javachatdatabase"
        , uniqueConstraints = @UniqueConstraint(columnNames="email")
)
public class User  implements java.io.Serializable {

    @Id
    @Column(name="phone_number", unique=true, nullable=false, length=20)
    private String userPhoneNumber;
    @Column(name="first_name", nullable=false, length=20)
    private String firstName;
    @Column(name="lastName", nullable=false, length=20)
    private String lastName;
    @Column(name="email", unique=true, nullable=false, length=45)
    private String email;
    @Column(name="image")
    private byte[] image;
    @Column(name="password", nullable=false, length=20)
    private String password;
    @Column(name="status", nullable=false, length=20)
    private String status;
    @Column(name="country", nullable=false, length=20)
    private String country;
    @Column(name="gender", nullable=false, length=20)
    private String gender;
    @Column(name="date_birth", nullable=false, length=10)
    private Date dateBirth;
    @Column(name="bio", nullable=false, length=50)
    private String bio;
    @Column(name="admin_flag", nullable=false)
    private int adminFlag;
    @Column(name="usercol", length=45)
    private String usercol;
    @OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    private Set<UserInvitation> userInvitations = new HashSet<UserInvitation>(0);
    @OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    private Set<UserContact> userContacts = new HashSet<UserContact>(0);
    @OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    private Set<MessageSettings> messageSettingses = new HashSet<MessageSettings>(0);
    @OneToMany(fetch=FetchType.LAZY, mappedBy="user",cascade = {CascadeType.REMOVE})
    private Set<UserGroupChat> userGroupChats = new HashSet<UserGroupChat>(0);

    public User() {
    }


    public User(String phoneNumber, String firstName, String lastName, String email, String password, String status, String country, String gender, Date dateBirth, String bio, int adminFlag) {
        this.userPhoneNumber = phoneNumber;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.password = password;
        this.status = status;
        this.country = country;
        this.gender = gender;
        this.dateBirth = dateBirth;
        this.bio = bio;
        this.adminFlag = adminFlag;
    }
    public User(String phoneNumber, String firstName, String lastName, String email, byte[] image, String password, String status, String country, String gender, Date dateBirth, String bio, int adminFlag, String usercol, Set<UserInvitation> userInvitations, Set<UserContact> userContacts, Set<MessageSettings> messageSettingses, Set<UserGroupChat> userGroupChats) {
        this.userPhoneNumber = phoneNumber;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.image = image;
        this.password = password;
        this.status = status;
        this.country = country;
        this.gender = gender;
        this.dateBirth = dateBirth;
        this.bio = bio;
        this.adminFlag = adminFlag;
        this.usercol = usercol;
        this.userInvitations = userInvitations;
        this.userContacts = userContacts;
        this.messageSettingses = messageSettingses;
        this.userGroupChats = userGroupChats;
    }



    public String getPhno() {
        return this.userPhoneNumber;
    }

    public void setPhno(String userPhoneNumber) {
        this.userPhoneNumber = userPhoneNumber;
    }


    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }


    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }


    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }


    public byte[] getImage() {
        return this.image;
    }

    public void setImage(byte[] image) {
        this.image = image;
    }


    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }


    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }


    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }


    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    @Temporal(TemporalType.DATE)
    public Date getDateBirth() {
        return this.dateBirth;
    }

    public void setDateBirth(Date dateBirth) {
        this.dateBirth = dateBirth;
    }


    public String getBio() {
        return this.bio;
    }

    public void setBio(String bio) {
        this.bio = bio;
    }


    public int getAdminFlag() {
        return this.adminFlag;
    }

    public void setAdminFlag(int adminFlag) {
        this.adminFlag = adminFlag;
    }


    public String getUsercol() {
        return this.usercol;
    }

    public void setUsercol(String usercol) {
        this.usercol = usercol;
    }

    public Set<UserInvitation> getUserInvitations() {
        return this.userInvitations;
    }

    public void setUserInvitations(Set<UserInvitation> userInvitations) {
        this.userInvitations = userInvitations;
    }

    public Set<UserContact> getUserContacts() {
        return this.userContacts;
    }

    public void setUserContacts(Set<UserContact> userContacts) {
        this.userContacts = userContacts;
    }

    public Set<MessageSettings> getMessageSettingses() {
        return this.messageSettingses;
    }

    public void setMessageSettingses(Set<MessageSettings> messageSettingses) {
        this.messageSettingses = messageSettingses;
    }

    public Set<UserGroupChat> getUserGroupChats() {
        return this.userGroupChats;
    }

    public void setUserGroupChats(Set<UserGroupChat> userGroupChats) {
        this.userGroupChats = userGroupChats;
    }




}


