package com.iti.ChatCommanServices.model.entity.user;
// Generated Mar 7, 2019 7:51:46 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserInvitationId generated by hbm2java
 */
@Embeddable
public class UserInvitationId implements java.io.Serializable {


     private String receiverPhoneNumber;
     private String senderPhoneNumber;

    public UserInvitationId() {
    }

    public UserInvitationId(String receiverPhoneNumber, String senderPhoneNumber) {
       this.receiverPhoneNumber = receiverPhoneNumber;
       this.senderPhoneNumber = senderPhoneNumber;
    }
   


    @Column(name="receiver_phone_number", nullable=false, length=20)
    public String getReceiverPhoneNumber() {
        return this.receiverPhoneNumber;
    }
    
    public void setReceiverPhoneNumber(String receiverPhoneNumber) {
        this.receiverPhoneNumber = receiverPhoneNumber;
    }


    @Column(name="sender_phone_number", nullable=false, length=20)
    public String getSenderPhoneNumber() {
        return this.senderPhoneNumber;
    }
    
    public void setSenderPhoneNumber(String senderPhoneNumber) {
        this.senderPhoneNumber = senderPhoneNumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserInvitationId) ) return false;
		 UserInvitationId castOther = ( UserInvitationId ) other; 
         
		 return ( (this.getReceiverPhoneNumber()==castOther.getReceiverPhoneNumber()) || ( this.getReceiverPhoneNumber()!=null && castOther.getReceiverPhoneNumber()!=null && this.getReceiverPhoneNumber().equals(castOther.getReceiverPhoneNumber()) ) )
 && ( (this.getSenderPhoneNumber()==castOther.getSenderPhoneNumber()) || ( this.getSenderPhoneNumber()!=null && castOther.getSenderPhoneNumber()!=null && this.getSenderPhoneNumber().equals(castOther.getSenderPhoneNumber()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getReceiverPhoneNumber() == null ? 0 : this.getReceiverPhoneNumber().hashCode() );
         result = 37 * result + ( getSenderPhoneNumber() == null ? 0 : this.getSenderPhoneNumber().hashCode() );
         return result;
   }   


}


