package com.iti.ChatCommanServices.model.entity.user;
// Generated Mar 7, 2019 7:51:46 PM by Hibernate Tools 4.3.1


import com.iti.ChatCommanServices.model.entity.user.User;
import com.iti.ChatCommanServices.model.entity.user.UserInvitationId;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserInvitation generated by hbm2java
 */
@Entity
@Table(name="user_invitation"
        ,catalog="javachatdatabase"
)
public class UserInvitation  implements java.io.Serializable {


    private UserInvitationId id;
    private User user;
    private boolean ignoreFlag;

    public UserInvitation() {
    }

    public UserInvitation(UserInvitationId id, User user, boolean ignoreFlag) {
        this.id = id;
        this.user = user;
        this.ignoreFlag = ignoreFlag;
    }

    @EmbeddedId


    @AttributeOverrides( {
            @AttributeOverride(name="receiverPhoneNumber", column=@Column(name="receiver_phone_number", nullable=false, length=20) ),
            @AttributeOverride(name="senderPhoneNumber", column=@Column(name="sender_phone_number", nullable=false, length=20) ) } )
    public UserInvitationId getId() {
        return this.id;
    }

    public void setId(UserInvitationId id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sender_phone_number", nullable=false, insertable=false, updatable=false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }


    @Column(name="ignore_flag", nullable=false)
    public boolean isIgnoreFlag() {
        return this.ignoreFlag;
    }

    public void setIgnoreFlag(boolean ignoreFlag) {
        this.ignoreFlag = ignoreFlag;
    }




}


