package com.iti.ChatCommanServices.model.entity.user;
// Generated Mar 7, 2019 7:51:46 PM by Hibernate Tools 4.3.1


import com.iti.ChatCommanServices.model.entity.user.User;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserContact generated by hbm2java
 */
@Entity
@Table(name="user_contact"
        ,catalog="javachatdatabase"
)
public class UserContact  implements java.io.Serializable {


    private UserContactId id;
    private User user;

    public UserContact() {
    }

    public UserContact(UserContactId id, User user) {
        this.id = id;
        this.user = user;
    }

    @EmbeddedId


    @AttributeOverrides( {
            @AttributeOverride(name="contact", column=@Column(name="contact", nullable=false, length=20) ),
            @AttributeOverride(name="phoneNumber", column=@Column(name="phone_number", nullable=false, length=20) ) } )
    public UserContactId getId() {
        return this.id;
    }

    public void setId(UserContactId id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="phone_number", nullable=false, insertable=false, updatable=false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }




}


