//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.25 at 09:43:33 PM EET 
//


package com.iti.client.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for MessageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MessageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Sender" type="{}userType"/>
 *         &lt;element name="MessageContent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MessageSettings" type="{}MessageSettingsType"/>
 *         &lt;element name="messagetimeStamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageType", propOrder = {
    "sender",
    "messageContent",
    "messageSettings",
    "messagetimeStamp"
})
public class MessageType {

    @XmlElement(name = "Sender", required = true)
    protected UserType sender;
    @XmlElement(name = "MessageContent", required = true)
    protected String messageContent;
    @XmlElement(name = "MessageSettings", required = true)
    protected MessageSettingsType messageSettings;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar messagetimeStamp;

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link UserType }
     *     
     */
    public UserType getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserType }
     *     
     */
    public void setSender(UserType value) {
        this.sender = value;
    }

    /**
     * Gets the value of the messageContent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageContent() {
        return messageContent;
    }

    /**
     * Sets the value of the messageContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageContent(String value) {
        this.messageContent = value;
    }

    /**
     * Gets the value of the messageSettings property.
     * 
     * @return
     *     possible object is
     *     {@link MessageSettingsType }
     *     
     */
    public MessageSettingsType getMessageSettings() {
        return messageSettings;
    }

    /**
     * Sets the value of the messageSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageSettingsType }
     *     
     */
    public void setMessageSettings(MessageSettingsType value) {
        this.messageSettings = value;
    }

    /**
     * Gets the value of the messagetimeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMessagetimeStamp() {
        return messagetimeStamp;
    }

    /**
     * Sets the value of the messagetimeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMessagetimeStamp(XMLGregorianCalendar value) {
        this.messagetimeStamp = value;
    }

}
