//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.25 at 09:43:33 PM EET 
//


package com.iti.client.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MessageSettingsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MessageSettingsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fontSize" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="fontStyle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="color" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bold" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="italic" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="underline" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="textBackground" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageSettingsType", propOrder = {
    "fontSize",
    "fontStyle",
    "color",
    "bold",
    "italic",
    "underline",
    "textBackground"
})
public class MessageSettingsType {

    protected float fontSize;
    @XmlElement(required = true)
    protected String fontStyle;
    @XmlElement(required = true)
    protected String color;
    protected boolean bold;
    protected boolean italic;
    protected boolean underline;
    @XmlElement(required = true)
    protected String textBackground;

    /**
     * Gets the value of the fontSize property.
     * 
     */
    public float getFontSize() {
        return fontSize;
    }

    /**
     * Sets the value of the fontSize property.
     * 
     */
    public void setFontSize(float value) {
        this.fontSize = value;
    }

    /**
     * Gets the value of the fontStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFontStyle() {
        return fontStyle;
    }

    /**
     * Sets the value of the fontStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFontStyle(String value) {
        this.fontStyle = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the bold property.
     * 
     */
    public boolean isBold() {
        return bold;
    }

    /**
     * Sets the value of the bold property.
     * 
     */
    public void setBold(boolean value) {
        this.bold = value;
    }

    /**
     * Gets the value of the italic property.
     * 
     */
    public boolean isItalic() {
        return italic;
    }

    /**
     * Sets the value of the italic property.
     * 
     */
    public void setItalic(boolean value) {
        this.italic = value;
    }

    /**
     * Gets the value of the underline property.
     * 
     */
    public boolean isUnderline() {
        return underline;
    }

    /**
     * Sets the value of the underline property.
     * 
     */
    public void setUnderline(boolean value) {
        this.underline = value;
    }

    /**
     * Gets the value of the textBackground property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextBackground() {
        return textBackground;
    }

    /**
     * Sets the value of the textBackground property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextBackground(String value) {
        this.textBackground = value;
    }

}
